version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/

  migrate:
    image: migrate/migrate
    entrypoint: ["/bin/sh", "-c", "migrate -path /migrations -database postgres://$DB_USER:$DB_PASS@postgres:5432/$DB_NAME?sslmode=disable up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  nginx:
    image: nginx:stable-alpine3.17-slim
    depends_on:
      - backend
    environment:
      - VITE_API_ENDPOINT_BASE=http://localhost:8000/api/v1
      - VITE_WS_ENDPOINT=ws://localhost:8000
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/dist
    ports:
      - "8000:80"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  centrifugo:
    image: centrifugo/centrifugo:v5.2.0
    environment:
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_API_KEY}
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=${CENTRIFUGO_TOKEN_HMAC_SECRET_KEY}
    command: centrifugo -c config.json --swagger
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    ports:
      - "3000:8000"
volumes:
  postgresdata:
    driver: local
